# emscripten.toolchain.cmake
cmake_minimum_required(VERSION 3.15)

set(CMAKE_SYSTEM_NAME Emscripten)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_C_COMPILER "$ENV{EMSDK}/upstream/emscripten/emcc")
set(CMAKE_CXX_COMPILER "$ENV{EMSDK}/upstream/emscripten/em++")
set(CMAKE_AR "$ENV{EMSDK}/upstream/emscripten/emar")
set(CMAKE_RANLIB "$ENV{EMSDK}/upstream/emscripten/emranlib")

set(CMAKE_CXX_COMPILER_AR ${CMAKE_AR})
set(CMAKE_CXX_COMPILER_RANLIB ${CMAKE_RANLIB})

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -sWASM=1 -pthread -matomics")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -sUSE_PTHREADS=1 -pthread -matomics")

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -sUSE_PTHREADS=1 -sALLOW_MEMORY_GROWTH=1 -sEXIT_RUNTIME -sPTHREAD_POOL_SIZE=3 -sWASM=1 -sFULL_ES3=1")

set(CMAKE_FIND_ROOT_PATH "$ENV{EMSDK}/upstream/emscripten/cache/sysroot")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(EMSCRIPTEN 1)